# Generated by Django 5.2 on 2026-01-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_author_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', max_length=500, null=True),
        ),
    ]
